name: RunicPvP
version: ${project.version}
main: com.runicrealms.plugin.pvp.RunicPvP
api-version: 1.15
authors: [ Skyfallin ]
depend:
  - MythicMobs
  - HolographicDisplays
  - RunicCore
  - RunicChat
  - RunicItems
  - RunicNpcs
  - RunicRestart
  - RunicCommon
  - RunicDatabase
commands:
  duel:
    usage: /<commands>
    description: Base for all duel commands